[package]
name = "voxel-engine"
version = "0.0.1"
edition = "2021"

[dependencies]
winit = "0.28"
env_logger = "0.10"
log = "0.4"
wgpu = "0.17"
futures = "0.3.28"
bytemuck = { version = "*", features = [ "derive" ] }
image = "0.24.7"
nalgebra = "0.32.3"
anyhow = "1.0"
noise = "0.8.2"
